spring:
  datasource:
    url: jdbc:h2:file:./h2/orders;AUTO_SERVER=TRUE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  config:
    import: "optional:file:./bot-config.yml"   # или file:/etc/bot/bot-config.yml в проде
  application:
    name: spring-telegram-bot-webhook-redis
  data:


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  h2:
    console:
      enabled: true
      path: /h2-console

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}
    username: ${TELEGRAM_BOT_USERNAME:}
    allowedUserIds: ${TELEGRAM_ALLOWED_USER_IDS:}
  flow:
    dispatcherContact: ${TELEGRAM_DISPATCHER_CONTACT:@dog_dispatcher}
    jobFormUrl: ${TELEGRAM_JOB_FORM_URL:}
    adminChatId: ${TELEGRAM_ADMIN_CHAT_ID:}
  webhook:
    url: ${TELEGRAM_WEBHOOK_URL:}
    secretToken: ${TELEGRAM_WEBHOOK_SECRET:supersecret}
    path: /webhook/telegram
